In [48]:
import pandas as pd
import os

In [49]:
RESULT_FINAL_DIR = 'result/'

In [50]:
result = pd.read_csv(os.path.join(RESULT_FINAL_DIR, 'result.csv'))

In [51]:
result.groupby('skenario').mean().sort_values('f1_score', ascending=False)

C:\Users\KEY\AppData\Local\Temp\ipykernel_10772\2433715885.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  result.groupby('skenario').mean().sort_values('f1_score', ascending=False)

                          fold  accuracy  precision    recall  f1_score
skenario
_clean_feature_            3.0  0.865698   0.842610  0.900000  0.870174
_clean_feature_onehot_1_   3.0  0.866279   0.850134  0.889535  0.869240
_clean_onehot_2_           3.0  0.862209   0.838428  0.897674  0.866951
_clean_                    3.0  0.861628   0.839626  0.894186  0.866018
_clean_feature_onehot_2_   3.0  0.861628   0.846336  0.883721  0.864604
_clean_onehot_1_           3.0  0.859302   0.839748  0.888372  0.863330
_feature_onehot_2_         3.0  0.825538   0.815559  0.842462  0.828480
_onehot_2_                 3.0  0.820615   0.803605  0.848615  0.825462
_feature_onehot_1_         3.0  0.810769   0.784152  0.857846  0.819283
_onehot_1_                 3.0  0.806769   0.773409  0.868923  0.817827
_                          3.0  0.803692   0.770107  0.868308  0.815660
_feature_                  3.0  0.807692   0.785362  0.848000  0.815039

In [55]:
result.groupby('skenario').mean().reset_index().to_excel(
    os.path.join(RESULT_FINAL_DIR, 'result.xlsx'), index=False)

C:\Users\KEY\AppData\Local\Temp\ipykernel_10772\4216107057.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  result.groupby('skenario').mean().reset_index().to_excel(

In [54]:
result.groupby('skenario').mean().reset_index()

C:\Users\KEY\AppData\Local\Temp\ipykernel_10772\3103365348.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  result.groupby('skenario').mean().reset_index()

                    skenario  fold  accuracy  precision    recall  f1_score
0                          _   3.0  0.803692   0.770107  0.868308  0.815660
1                    _clean_   3.0  0.861628   0.839626  0.894186  0.866018
2            _clean_feature_   3.0  0.865698   0.842610  0.900000  0.870174
3   _clean_feature_onehot_1_   3.0  0.866279   0.850134  0.889535  0.869240
4   _clean_feature_onehot_2_   3.0  0.861628   0.846336  0.883721  0.864604
5           _clean_onehot_1_   3.0  0.859302   0.839748  0.888372  0.863330
6           _clean_onehot_2_   3.0  0.862209   0.838428  0.897674  0.866951
7                  _feature_   3.0  0.807692   0.785362  0.848000  0.815039
8         _feature_onehot_1_   3.0  0.810769   0.784152  0.857846  0.819283
9         _feature_onehot_2_   3.0  0.825538   0.815559  0.842462  0.828480
10                _onehot_1_   3.0  0.806769   0.773409  0.868923  0.817827
11                _onehot_2_   3.0  0.820615   0.803605  0.848615  0.825462